### ISSUE TITLE
Exception when open Polyhedron 

### ISSUE THREAD

**Issue by kant2002** [c-ohle/RationalNumerics#6]
When opening Polyhedron tab on my PC. On other laptop tab was opening fine.
```
System.ArgumentException: Value does not fall within the expected range.
   at Test.DX11Ctrl.IDevice.CreatePixelShader(Byte* ShaderBytecode, IntPtr BytecodeLength, Void* ClassLinkage)
   at Test.DX11Ctrl.apply() in c:\RationalNumerics\Test\mini3d\DX11Ctrl.cs:line 388
   at Test.DX11Ctrl.DC.DrawMesh(VertexBuffer vb, IndexBuffer ib, Int32 i, Int32 n) in c:\RationalNumerics\Test\mini3d\DX11Ctrl.cs:line 1223
   at Test.DX11ModelCtrl.render(DC dc, Int32 was, Group[] nodes) in c:\RationalNumerics\Test\mini3d\DX11ModelCtrl.cs:line 86
   at Test.DX11ModelCtrl.OnRender(DC dc) in c:\RationalNumerics\Test\mini3d\DX11ModelCtrl.cs:line 107
   at Test.DX11Ctrl.Refresh() in c:\RationalNumerics\Test\mini3d\DX11Ctrl.cs:line 147
   at Test.DX11Ctrl.WndProc(Message& m) in c:\RationalNumerics\Test\mini3d\DX11Ctrl.cs:line 621
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Comment by kant2002** [comment]
My video card is `NVIDIA GeForce 210` where it fails. If some requirement are not met, maybe at least try/catch inside WndProc, so application would not crash.
